S10205253-web2021apr_p01_t5-47861006765e/Controllers/CompCreateController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web_Asg.DAL;
using Web_Asg.Models;

namespace Web_Asg.Controllers
{
    public class CompCreateController : Controller
    {
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();
        private CompetitionDAL compCreate = new CompetitionDAL();
        private CompetitionSubmissionDAL compSubContext = new CompetitionSubmissionDAL();
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Competition> comp = compCreate.GetAllComps();
            return View(comp);
        }
        //get all area of interests
        private List<SelectListItem> GetAreaInterest()
        {
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAi();
            List<SelectListItem> AreaInterest = new List<SelectListItem>();
            foreach (AreaInterest AI in areaInterestList)
            {
                AreaInterest.Add(new SelectListItem
                {
                    Value = Convert.ToString(AI.AreaInterestID),
                    Text = AI.Name
                });
            }
            return AreaInterest;
        }

        public ActionResult Create()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["AreaInterestList"] = GetAreaInterest();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competition comp)
        {
            if (ModelState.IsValid)
            {
                comp.CompetitionID = compCreate.AddComp(comp);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(comp);
            }

        }
        public ActionResult Edit(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            Competition comp = compCreate.GetDetails(id);
            //get amt of competitors
            List<CompetitionSubmission> Competitors = compSubContext.GetAllSubmissionsByComp(comp.CompetitionID);
            ViewData["competitorCount"] = Competitors.Count();
            return View(comp);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Competition comp)
        {
            compCreate.Update(comp);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            Competition comp = compCreate.GetDetails(id);
            List<CompetitionSubmission> Competitors = compSubContext.GetAllSubmissionsByComp(comp.CompetitionID);
            ViewData["competitorCount"] = Competitors.Count();
            return View(comp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Competition comp)
        {
            compCreate.Delete(comp.CompetitionID);
            return RedirectToAction("Index");
        }
    }
}

S10205253-web2021apr_p01_t5-47861006765e/Views/CompCreate/Create.cshtml
@model Web_Asg.Models.Competition

@{
    ViewData["Title"] = "Create";
}

<h1>Index</h1>

<h4>Competition</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AreaInterestID"
                       class="col-sm-3 col-form-label">AreaInterest</label>
                <div class="col-sm-9 col-md-5">
                    <select asp-for="AreaInterestID"
                            asp-items="@ViewData["AreaInterestList"]
                                as List<SelectListItem>"
                            class="form-control-lg">
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CompetitionName" class="control-label"></label>
                <input asp-for="CompetitionName" class="form-control" required />
                <span asp-validation-for="CompetitionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" required />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" required />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultReleasedDate" class="control-label"></label>
                <input asp-for="ResultReleasedDate" class="form-control" required />
                <span asp-validation-for="ResultReleasedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-action="Create" type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

S10205253-web2021apr_p01_t5-47861006765e/Views/CompCreate/Delete.cshtml
@model Web_Asg.Models.Competition

@{
    ViewData["Title"] = "Delete";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <h1 class="mb-2">Delete Competitions</h1>

    <h3 class="mb-4">Are you sure you want to delete this?</h3>
    <div>
        <form asp-action="Delete">
            <fieldset class="FormContent">
                <div class="form-group row">
                    <div class="form-group">
                        <input type="hidden" asp-for="CompetitionID" />
                        <input type="hidden" asp-for="AreaInterestID" />
                        <label asp-for="CompetitionName" class="control-label"></label>
                        <input asp-for="CompetitionName" class="form-control" readonly />
                        <input type="hidden" asp-for="StartDate" />
                        <input type="hidden" asp-for="EndDate" />
                        <input type="hidden" asp-for="ResultReleasedDate" />
                    </div>
                </div>
            </fieldset>
            <input id="Delete" type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-primary" asp-action="Index">Back to List</a>
        </form>
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        if (@ViewData["competitorCount"] > 0) {
        alert("there are competitors in this competition")
            $("#Delete").prop("disabled", true);
        }
    }); 
</script>

S10205253-web2021apr_p01_t5-47861006765e/Views/CompCreate/Edit.cshtml
@model Web_Asg.Models.Competition

@{
    ViewData["Title"] = "Edit";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <h1>Edit Competition Details</h1>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <input type="hidden" asp-for="CompetitionID" />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="AreaInterestID" />
                </div>
                <div class="form-group">
                    <label asp-for="CompetitionName" class="control-label"></label>
                    <input asp-for="CompetitionName" class="form-control" />
                    <span asp-validation-for="CompetitionName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label"></label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ResultReleasedDate" class="control-label"></label>
                    <input asp-for="ResultReleasedDate" class="form-control" />
                    <span asp-validation-for="ResultReleasedDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input id="Save" type="submit" value="Save" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a class="btn  btn-primary" asp-action="Index">Back to List</a>
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        if (@ViewData["competitorCount"] > 0) {
            alert("there are competitors in this competition")
            $("#Save").prop("disabled", true);
        }
    });
</script>

S10205253-web2021apr_p01_t5-47861006765e/Views/CompCreate/Index.cshtml
@model IEnumerable<Web_Asg.Models.Competition>
@{
    ViewData["Title"] = "Index";
}

<h1 class="mb-4">Competitions</h1>

@if (Model.ToList().Count > 0)
{
    <a class="btn btn-primary mb-5" asp-action="Create" asp-controller="CompCreate">Create Comp</a>
<div class="table-responsive">
    <table id="viewStaff" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Result Release Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var comp in Model)
            {
                <tr>
                    <td>@comp.CompetitionName</td>
                    <td>@comp.StartDate</td>
                    <td>@comp.EndDate</td>
                    <td>@comp.ResultReleasedDate</td>
                    <td>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="CompCreate"
                           asp-route-id="@comp.CompetitionID">Delete Comp</a> 
                        <a class="btn btn-info" asp-action="Edit" asp-controller="CompCreate"
                           asp-route-id="@comp.CompetitionID">Edit Comp</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
}
else
{
<span style="color:red">No record found!</span>
}