S10205253-web2021apr_p01_t5-47861006765e/Models/CompetitionJudge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Web_Asg.Models
{
    public class CompetitionJudge
    {
        public int CompetitionID { get; set; }
        public int JudgeID { get; set; }

    }
}

S10205253-web2021apr_p01_t5-47861006765e/Models/CompetitionJudgeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Web_Asg.Models
{
    public class AvailJudges
    {
        public string JudgeName { get; set; }
        public int JudgeID { get; set; }
        public bool Selected { get; set; }
    }
    public class CompetitionJudgeViewModel
    {
        [Required]
        public int CompetitionID { get; set; }

        public List<AvailJudges> Judges { get; set; }

        public List<int> JudgeID { get; set; }


    }
}

S10205253-web2021apr_p01_t5-47861006765e/Controllers/CompetitionJudgeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_Asg.DAL;
using Web_Asg.Models;

namespace Web_Asg.Controllers
{
    public class CompetitionJudgeController : Controller
    {
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private AreaInterestDAL AreaInterestContext = new AreaInterestDAL();
        private JudgeDAL JudgeContext = new JudgeDAL();
        private CompetitionJudgeDAL CompJudgeContext = new CompetitionJudgeDAL();
        //get all comps from comp DAL
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Competition> compList = competitionContext.GetAllComps();
            return View(compList);
        }
        
        public ActionResult AssignJudges(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionJudge> currentJudgeList = CompJudgeContext.GetCompJudges(id);
            List<string> currentJudgeName = new List<string>();
            Competition comp = competitionContext.GetDetails(id);
            AreaInterest areaInterest = AreaInterestContext.GetDetails(comp.AreaInterestID);
            //get judges alr assigned if any
            foreach (CompetitionJudge cj in currentJudgeList)
            {
                currentJudgeName.Add(JudgeContext.GetDetails(cj.JudgeID).JudgeName);
            }
            ViewData["AreaInterest"] = areaInterest;
            ViewData["Comp"] = comp;
            ViewData["JudgeCount"] = CompJudgeContext.JudgeCount(id);
            ViewData["CurrentJudges"] = CompJudgeContext.GetCompJudges(id);
            ViewData["CurrentJudgeName"] = currentJudgeName;
            CompetitionJudgeViewModel compJudge = new CompetitionJudgeViewModel
            {
                Judges = GetJudges(comp)
            };
            return View(compJudge);
        }
        // get all available judges 
        private List<AvailJudges> GetJudges(Competition comp)
        {
            List<Judge> judgeList = JudgeContext.GetAllJudges();
            List<AvailJudges> jSelectList = new List<AvailJudges>();
            foreach (Judge j in judgeList)
            {
                if (j.AreaInterestID == comp.AreaInterestID)
                {
                    jSelectList.Add(new AvailJudges
                    {
                        JudgeName = j.JudgeName,
                        JudgeID = j.JudgeID,
                        Selected = false
                    });
                }
            }
            return jSelectList;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignJudges(CompetitionJudgeViewModel cJudge)
        {
            //get all the selected judges and insert to database
            foreach (AvailJudges judgeItem in cJudge.Judges)
            {
                if (judgeItem.Selected)
                {
                    cJudge.JudgeID.Add(judgeItem.JudgeID);
                }
            }
            CompJudgeContext.AddCompJudge(cJudge);
            return RedirectToAction("Index");
        }

      
        public ActionResult Delete(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            Competition comp = competitionContext.GetDetails(id);
            AreaInterest areaInterest = AreaInterestContext.GetDetails(comp.AreaInterestID);
            List<AvailJudges> availableJudges = new List<AvailJudges>();
            List<CompetitionJudge> compJudge = CompJudgeContext.GetCompJudges(id);
            foreach (CompetitionJudge cj in compJudge)
            {
                availableJudges.Add(new AvailJudges
                {
                    JudgeName = JudgeContext.GetDetails(cj.JudgeID).JudgeName,
                    JudgeID = cj.JudgeID,
                    Selected = false
                });
            }
            ViewData["AreaInterest"] = areaInterest;
            ViewData["Comp"] = comp;
            CompetitionJudgeViewModel compJudges = new CompetitionJudgeViewModel
            {
                Judges = availableJudges
            };
            return View(compJudges);
        }

        // POST: CompetitionJudge/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(CompetitionJudgeViewModel cJudge)
        {
            foreach (AvailJudges judgeItem in cJudge.Judges)
            {
                if (judgeItem.Selected)
                {
                    cJudge.JudgeID.Add(judgeItem.JudgeID);
                }
            }
            CompJudgeContext.Delete(cJudge);
            return RedirectToAction("Index");
        }
    }
}

S10205253-web2021apr_p01_t5-47861006765e/Views/CompetitionJudge/AssignJudges.cshtml
@model Web_Asg.Models.CompetitionJudgeViewModel

@{
    ViewData["Title"] = "AssignJudges";
    AreaInterest AI = ViewData["AreaInterest"] as AreaInterest;
    Competition comp = ViewData["Comp"] as Competition;
    List<CompetitionJudge> compJudge = ViewData["CurrentJudges"] as List<CompetitionJudge>;
    List<string> CurrentJudgeName = ViewData["CurrentJudgeName"] as List<string>;
    int JudgeCount = Convert.ToInt32(ViewData["JudgeCount"]);
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AssignJudges</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <h1>AssignJudges</h1>

    <h4>CompetitionJudge</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="AssignJudges">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label for="AreaInterestID" class="control-label">AreaInterestID</label>
                    <input id="AreaInterestID" value="@AI.AreaInterestID" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label for="AreaInterestName" class="control-label">AreaInterest</label>
                    <input class="form-control" id="AreaInterestName" value="@AI.Name" readonly />
                </div>
                <div class="form-group">
                    <label for="CompetitionID" class="control-label">Competition ID</label>
                    <input asp-for="CompetitionID" id="CompetitionID" value="@comp.CompetitionID" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label for="CompetitionName" class="control-label">Competition</label>
                    <input id="CompetitionName" value="@comp.CompetitionName" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <input hidden id="CompetitionEndDate" value="@comp.EndDate" class="form-control" readonly />
                </div>
                <div class="form-group">
                    @for (int i = 0; i < CurrentJudgeName.Count; i++)
                    {
                        <p hidden class="CurrentJudgeName">@CurrentJudgeName[i]</p>
                    }
                </div>
                <div class="form-group">
                    <label for="AreaInterestName" class="control-label">Available Judges</label><br />
                    @for (int i = 0; i < Model.Judges.Count; i++)
                    {
                        <input id="@Model.Judges[i].JudgeName" class="Checkbox" asp-for="Judges[i].Selected" type="checkbox" />
                        <label for="checkbox" asp-for="Judges[i].Selected">@Model.Judges[i].JudgeName</label>
                        <input type="hidden" asp-for="Judges[i].JudgeID" />
                        <input type="hidden" asp-for="Judges[i].JudgeName" />
                    }
                </div>
                <input type="hidden" asp-for="JudgeID" />
                <div class="form-group">
                    <input id="Assign" disabled type="submit" value="Assign" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        var today = new Date();
        var dd = String(today.getDate()).padStart(2, '0');
        var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
        var yyyy = today.getFullYear();
        var endDateString = $("#CompetitionEndDate").val();
        today = mm + '/' + dd + '/' + yyyy;
        var todayDate = new Date(today);
        var endDate = new Date(endDateString);
        if (todayDate > endDate) {
            alert("Competition is already over");
        }
        else {
            var CurrentJudgeName = [];
        $(".CurrentJudgeName").each(function () {
            CurrentJudgeName.push($(this).text());
        });
        $(".Checkbox").click(function () {
            var checked = $("input:checked").length;
            var selectName = $(this).attr('id');
            for (var i = 0; i < CurrentJudgeName.length; i++) {
                if (CurrentJudgeName[i] == selectName) {
                    alert("Judge is already assigned to tjis competition")
                    $(this).prop('checked', false)
                }
            }
            if (checked + @JudgeCount >= 2) {
                $("#Assign").prop("disabled", false);
            }
            else {
                $("#Assign").prop("disabled", true);
            }
        });
        }

    });
</script>

S10205253-web2021apr_p01_t5-47861006765e/Views/CompetitionJudge/Delete.cshtml
@model Web_Asg.Models.CompetitionJudgeViewModel

@{
    ViewData["Title"] = "Delete";
    AreaInterest AI = ViewData["AreaInterest"] as AreaInterest;
    Competition comp = ViewData["Comp"] as Competition;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AssignJudges</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <h1>Assign Competition Judges</h1>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Delete">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label for="AreaInterestID" class="control-label">AreaInterestID</label>
                    <input id="AreaInterestID" value="@AI.AreaInterestID" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label for="AreaInterestName" class="control-label">AreaInterest</label>
                    <input class="form-control" id="AreaInterestName" value="@AI.Name" readonly />
                </div>
                <div class="form-group">
                    <label for="CompetitionID" class="control-label">Competition ID</label>
                    <input asp-for="CompetitionID" id="CompetitionID" value="@comp.CompetitionID" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label for="CompetitionName" class="control-label">Competition</label>
                    <input id="CompetitionName" value="@comp.CompetitionName" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label for="AreaInterestName" class="control-label">Available Judges</label><br />
                    @for (int i = 0; i < Model.Judges.Count; i++)
                    {
                        <input class="Checkbox" asp-for="Judges[i].Selected" type="checkbox" />
                        <label asp-for="Judges[i].Selected">@Model.Judges[i].JudgeName</label>
                        <input type="hidden" asp-for="Judges[i].JudgeID" />
                        <input type="hidden" asp-for="Judges[i].JudgeName" />
                    }
                </div>
                <input type="hidden" asp-for="JudgeID" />
                <div class="form-group">
                    <input id="Delete"  type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </div>
</body>
</html>
@*<script>
    $(document).ready(function () {
        $(".Checkbox").click(function () {
            var checked = $("input:checked").length;
            if (checked >= 2) {
                $("#Assign").prop("disabled", false);
            }
        });
    });
</script>*@

S10205253-web2021apr_p01_t5-47861006765e/Views/CompetitionJudge/Index.cshtml
@model IEnumerable<Web_Asg.Models.Competition>

@{
    ViewData["Title"] = "Index";
}

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Result Release Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comp in Model)
                {
                <tr>
                    <td>@comp.CompetitionName</td>
                    <td>@comp.StartDate</td>
                    <td>@comp.EndDate</td>
                    <td>@comp.ResultReleasedDate</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Assignjudges" asp-controller="CompetitionJudge"
                           asp-route-id="@comp.CompetitionID">Assign Judges</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="CompetitionJudge"
                           asp-route-id="@comp.CompetitionID">Remove Judges</a> 
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}