S10205253-web2021apr_p01_t5-47861006765e/Models/AreaInterest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Web_Asg.Models
{
    public class AreaInterest
    {
        [Key]
        [Display(Name = "ID")]
        public int AreaInterestID { get; set; }

        [Display(Name = "Area of Interest")]
        [Required]
        public string Name { get; set; }

    }
}

S10205253-web2021apr_p01_t5-47861006765e/Models/AreaInterestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

//Might have to delete later 
namespace Web_Asg.Models
{
    public class AreaInterestViewModel
    {
        [Key]
        [Display(Name = "ID")]
        public int AreaInterestID { get; set; }

        [Display(Name = "Area of Interest")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Competition No: ")]
        [Required]
        public int CompNo { get; set; }
        //public List<AreaInterest> AreaInterestList { get; set; }
        //public List<Competition> compList { get; set; }
        //public AreaInterestViewModel()
        //{
        //    AreaInterestList = new List<AreaInterest>();
        //    compList = new List<Competition>();
        //}
    }
}

S10205253-web2021apr_p01_t5-47861006765e/Controllers/AreaInterestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_Asg.DAL;
using Web_Asg.Models;

namespace Web_Asg.Controllers
{
    public class AreaInterestController : Controller
    {
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();
        private AreaInterestDAL CompAmt = new AreaInterestDAL();
        private CompetitionDAL compContext = new CompetitionDAL();
        //Get List of area of interests and pass to view
        public ActionResult Index()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<AreaInterest> areaInterestiList = areaInterestContext.GetAllAi();
            return View(areaInterestiList);
        }


        public ActionResult Create()
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        //Create Area Interest
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AreaInterest AI)
        {
            AI.AreaInterestID = areaInterestContext.Add(AI);
            return RedirectToAction("Index");
        }



        // GET: AreaInterestController/Delete/5
        public ActionResult Delete(int id)
        {
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            AreaInterest areaInterest = areaInterestContext.GetDetails(id);
            AreaInterestViewModel areaInterestVM = MapToAreaInterestVM(areaInterest);
            return View(areaInterestVM);
        }

        //make the view model 
        public AreaInterestViewModel MapToAreaInterestVM(AreaInterest areaInterest)
        {
            int id = 0;
            List<Competition> compList = compContext.GetAllComps();
            foreach (Competition c in compList)
            {
                if (areaInterest.AreaInterestID == c.AreaInterestID)
                {
                    id += 1;
                }
            }
            AreaInterestViewModel areaInterestVM = new AreaInterestViewModel
            {
                AreaInterestID = areaInterest.AreaInterestID,
                Name = areaInterest.Name,
                CompNo = id
            };
            return areaInterestVM;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(AreaInterestViewModel areaInterestVM)
        {
            if (areaInterestVM.CompNo == 0)
            {
                areaInterestContext.Delete(areaInterestVM.AreaInterestID);
            }
            //areaInterestContext.Delete(areaInterestVM.AreaInterestID);
            return RedirectToAction("Index");
        }
    }
}

S10205253-web2021apr_p01_t5-47861006765e/Views/AreaInterest/Create.cshtml
@model Web_Asg.Models.AreaInterest

@{
    ViewData["Title"] = "Create";
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <h1>Area Of Interests</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
                <a class="btn btn-primary" asp-action="Index">Back to List</a>
            </form>
        </div>
    </div>
</body>
</html>

S10205253-web2021apr_p01_t5-47861006765e/Views/AreaInterest/Delete.cshtml
@model Web_Asg.Models.AreaInterestViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Area Of Interests</h1>
<form asp-action="Delete">
    <div>
        <fieldset class="FormContent">
            <div class="form-group row">
                <div class="form-group">
                    <input type="hidden" asp-for="AreaInterestID" class="form-control-plaintext" readonly />
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <label asp-for="CompNo" class="control-label"></label>
                    <input asp-for="CompNo" class="form-control" readonly />
                </div>
            </div>
        </fieldset>
        @{ 
            if (Model.CompNo > 0 )
            {
                <h4 class="text-danger">Unable to delete there are competitions under this area of interest</h4>
            }
        }
        <input type="submit" value="Delete" class="btn btn-danger" 
               @{ if (Model.CompNo > 0)
                   {
                        @:disabled="disabled"
               } }/> |
        <a class="btn btn-primary" asp-action="Index">Back to List</a>

    </div>
</form>

S10205253-web2021apr_p01_t5-47861006765e/Views/AreaInterest/Index.cshtml
@model IEnumerable<Web_Asg.Models.AreaInterest>

@{
    ViewData["Title"] = "View Categories";
}
@{
    var data = ViewBag;
}

<style>
    .btn {
        border: 2px solid white;
        background-color: #f25939;
        color: white;
        padding: 12px 20px;
        font-size: 16px;
        cursor: pointer;
        color: white;
    }

        .btn:hover {
            background: white;
            color: #f25939;
        }
</style>

<div class="pt-5 align-content-center">
    <h1>View Categories</h1><br />
    <a class="btn" asp-action="Create">Create New Category</a>
</div>
<br/><br />

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered table-hover">
            <thead style="color: #949494">
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td style="width:min-content">
                            <a class="btn btn-danger" asp-action="Delete" asp-controller="AreaInterest"
                               asp-route-id="@item.AreaInterestID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}